# Generated by Django 2.1.5 on 2019-01-23 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='blog_img/')),
                ('content', models.TextField(max_length=2000)),
            ],
        ),
    ]
