# Generated by Django 2.1.5 on 2019-01-24 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='categorie',
            new_name='categ',
        ),
        migrations.AddField(
            model_name='post',
            name='post_cate',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='myblog.Categorie'),
            preserve_default=False,
        ),
    ]
